/** @type {import('./$types').PageLoad} */
export async function load({ fetch }) {
  const res = await fetch('/data/streamers.json');
  const streamers = await res.json();

  return {
    streamers,
  };
}

const MINS = 60;
export const config = {
  isr: {
    // Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
    // Setting the value to `false` means it will never expire.
    expiration: MINS * 5,
  },
};
